version: '3.8'

services:
  # Python Runner Service (for DataFrame comparison)
  python-runner:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: python-runner
    volumes:
      - ./data:/app/data        # HOST ./data/ -> CONTAINER /app/data
      - ./scripts:/app/scripts  # HOST ./scripts/ -> CONTAINER /app/scripts
    environment:
      - SPARK_MASTER_URL=spark://tester-spark-master:7077
    networks:
      - spark-net
    command: tail -f /dev/null  # Keep container running

networks:
  spark-net:
    driver: bridge
