version: '3.8'

services:
  # Python Runner Service (for DataFrame comparison)
  python-runner:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: python-runner
    restart: unless-stopped
    volumes:
      - ./data:/app/data        # HOST ./data/ -> CONTAINER /app/data
      - ./scripts:/app/scripts  # HOST ./scripts/ -> CONTAINER /app/scripts
    environment:
      - SPARK_MASTER_URL=spark://tester-spark-master:7077
    networks:
      - spark-net
    command: tail -f /dev/null  # Keep container running

  # REST API Service (for DataFrame operations via HTTP)
  dataframe-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: dataframe-api
    restart: unless-stopped
    ports:
      - "8651:5000"             # HOST:8651 -> CONTAINER:5000
    volumes:
      - ./data:/app/data        # HOST ./data/ -> CONTAINER /app/data
      - ./scripts:/app/scripts  # HOST ./scripts/ -> CONTAINER /app/scripts
    environment:
      - SPARK_MASTER_URL=spark://tester-spark-master:7077
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    networks:
      - spark-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # React UI Service (for web interface)
  dataframe-ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: dataframe-ui
    restart: unless-stopped
    ports:
      - "3123:3000"             # HOST:3000 -> CONTAINER:3000
    depends_on:
      - dataframe-api
    networks:
      - spark-net
    environment:
      - REACT_APP_API_URL=http://localhost:8651

networks:
  spark-net:
    driver: bridge
