name: CI - DataFrame Tester

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install Make
      run: sudo apt-get update && sudo apt-get install -y make

    - name: Run tests
      run: make test

    - name: Check service health
      run: make health

    - name: Show logs on failure
      if: failure()
      run: make logs

    - name: Cleanup
      if: always()
      run: make clean
