name: CI - DataFrame Tester

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install Make
      run: sudo apt-get update && sudo apt-get install -y make

    - name: Start services
      run: make start

    - name: Wait for services to be ready
      run: sleep 30

    - name: Run tests
      run: make test

    - name: Check service health
      run: make api-health

    - name: Stop services
      run: make stop
